### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by gitgrupoift** [fabiohcnobre/SNRHos#1]
Olá, sabe se a WSDL deles tem alguma chave para testes? Estou criando um client em PHP e queria testar.

**Comment by fabiohcnobre** [comment]
De teste eu nunca ouvi falar. Somente vi mesmo um  produção.
Mais testa em produção mesmo. Não tem problema.

**Comment by gitgrupoift** [comment]
Sensacionais os webservice de governos, hahahaha, valeu.

**Comment by fabiohcnobre** [comment]
Nossa até de mais da conta!
