### ISSUE TITLE
Want to update README.md file and adding CODE_OF_CONDUCT file 

### ISSUE THREAD

**Issue by sb-decoder** [fabiohcnobre/SNRHos#4]
I want to add how to contribute section and also contributors profile into main README.md file and want to add Code of conduct file

**Comment by sb-decoder** [comment]
@fabiohcnobre Do you want this?

**Comment by fabiohcnobre** [comment]
@sb-decoder 
hi
If you make a tutorial on read.me how to install the nuged package of this intention.

**Comment by fabiohcnobre** [comment]
thanks!!!
